### ISSUE TITLE
Install failed when using clusterpedia as subchart together with mysql

### ISSUE THREAD

**Issue by 27149chen** [clusterpedia-io/clusterpedia-helm#61]
### What happened?

Install failed when using clusterpedia as subchart together with mysql, error is:

```
NSTALLATION FAILED: template: ys1000/charts/mysql/templates/primary/svc.yaml:11:14: executing "ys1000/charts/mysql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: ys1000/charts/clusterpedia/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: ys1000/charts/clusterpedia/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### What did you expect to happen?

install succeeded

### How can we reproduce it (as minimally and precisely as possible)?

create a parent chart and add the following subcharts:
```
dependencies:
- name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 9.x.x
  condition: tags.mysql
- name: clusterpedia
  repository: https://clusterpedia-io.github.io/clusterpedia-helm
  version: 1.4.0
  condition: tags.clusterpedia
```
